cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    abcabcabc:
      email: abc@gmail.com
      logged_in: false
      name: A
      password: $2b$12$RShlq0jzxtxMgdswQiBUje32JLrBwHWlwyyS0evlA0vp7RPr2ta2K
    azharisn:
      email: ariazhari@ugm.ac.id
      failed_login_attempts: 0
      logged_in: false
      name: Azhari SN
      password: $2b$12$ErDLUndroUbOX6H/SBQoweyxKwEFzZBYHDb3v8CAVsgXDlfgK0r3u
preauthorized:
  emails:
  - andreasnotokusumo23@gmail.com
